
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author COOPERATIVE
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnBeefSeekhKabab = new javax.swing.JButton();
        jbtnHaleem = new javax.swing.JButton();
        jbtnChickenPulao = new javax.swing.JButton();
        jbtnBeefBurger = new javax.swing.JButton();
        jbtnChickenSeekh = new javax.swing.JButton();
        jbtnHotSpicyBiryani = new javax.swing.JButton();
        jbtnChickenBiryani = new javax.swing.JButton();
        jbtnChickenTikka = new javax.swing.JButton();
        jbtnZingerBurger = new javax.swing.JButton();
        jbtnChickenJalfrezi = new javax.swing.JButton();
        jbtnGajrela = new javax.swing.JButton();
        jbtnHotChilliPizza = new javax.swing.JButton();
        jbtnChickenKarahi = new javax.swing.JButton();
        jbtnGhullabJaman = new javax.swing.JButton();
        jbtnChickenBurger = new javax.swing.JButton();
        jbtnAlooSamoosa = new javax.swing.JButton();
        jbtnChickenSamoosa = new javax.swing.JButton();
        jbtnHalwaPuri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();
        jbtnAbout = new javax.swing.JButton();
        jbtnContactUs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 110));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 110));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 110));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 80, 110));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 110));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 110));

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, 110));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 80, 110));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, 110));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 80, 110));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 110));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 490));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBeefSeekhKabab.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnBeefSeekhKabab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Beef Seekh Kabab1.PNG"))); // NOI18N
        jbtnBeefSeekhKabab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBeefSeekhKababActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBeefSeekhKabab, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 120, 160));

        jbtnHaleem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnHaleem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Haleem-Pakistani-food.jpg"))); // NOI18N
        jbtnHaleem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHaleemActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHaleem, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 120, 160));

        jbtnChickenPulao.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenPulao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Pulao.jpg"))); // NOI18N
        jbtnChickenPulao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenPulaoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenPulao, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, 160));

        jbtnBeefBurger.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnBeefBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Beef Burger.jpg"))); // NOI18N
        jbtnBeefBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBeefBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBeefBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 160));

        jbtnChickenSeekh.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenSeekh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Seekh.jpg"))); // NOI18N
        jbtnChickenSeekh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenSeekhActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenSeekh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 160));

        jbtnHotSpicyBiryani.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnHotSpicyBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Hot Spicy Biryani.jpg"))); // NOI18N
        jbtnHotSpicyBiryani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHotSpicyBiryaniActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHotSpicyBiryani, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, 160));

        jbtnChickenBiryani.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Biryani.jpg"))); // NOI18N
        jbtnChickenBiryani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenBiryaniActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenBiryani, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 160));

        jbtnChickenTikka.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenTikka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Tikka.jpg"))); // NOI18N
        jbtnChickenTikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenTikkaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenTikka, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 160));

        jbtnZingerBurger.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnZingerBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Hot Spicy Zinger.png"))); // NOI18N
        jbtnZingerBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZingerBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnZingerBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 160));

        jbtnChickenJalfrezi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenJalfrezi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Jalfrezi.jpg"))); // NOI18N
        jbtnChickenJalfrezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenJalfreziActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenJalfrezi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 160));

        jbtnGajrela.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnGajrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Gajrela - Gajar Ka Halwa.jpg"))); // NOI18N
        jbtnGajrela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGajrelaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGajrela, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 160));

        jbtnHotChilliPizza.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnHotChilliPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_736-7362027_new-york-style-pizza-hd-png-download.png"))); // NOI18N
        jbtnHotChilliPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHotChilliPizzaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHotChilliPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 120, 160));

        jbtnChickenKarahi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenKarahi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Karahi.jpg"))); // NOI18N
        jbtnChickenKarahi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenKarahiActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenKarahi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 160));

        jbtnGhullabJaman.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnGhullabJaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Ghullab Jaman.jpg"))); // NOI18N
        jbtnGhullabJaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGhullabJamanActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGhullabJaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 120, 160));

        jbtnChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Burger1.PNG"))); // NOI18N
        jbtnChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 120, 160));

        jbtnAlooSamoosa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnAlooSamoosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Aloo Samoosa (3).png"))); // NOI18N
        jbtnAlooSamoosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlooSamoosaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAlooSamoosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 160));

        jbtnChickenSamoosa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnChickenSamoosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Chicken Samosa.jpg"))); // NOI18N
        jbtnChickenSamoosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenSamoosaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenSamoosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 160));

        jbtnHalwaPuri.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnHalwaPuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i01_Halwa Puri (2).jpg"))); // NOI18N
        jbtnHalwaPuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHalwaPuriActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHalwaPuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 790, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 350, 410));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, 40));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 40));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 180, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 170));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Payment Method");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Cash");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Change");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, 40));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 180, 40));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel5.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 180, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 420, 170));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 150, 50));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 50));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 40));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 420, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1380, 200));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP36DlTt", 1, 36)); // NOI18N
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 350, 70));

        jbtnAbout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnAbout.setText("About");
        jbtnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAboutActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jbtnContactUs.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jbtnContactUs.setText("Contact Us");
        jbtnContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContactUsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//===========================================FUNCTION=============================
    
    public void ItemCost()
    {
        double sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
            jtxtSubTotal.setText(Double.toString(sum));
            double cTotal1 =Double.parseDouble(jtxtSubTotal.getText());
            
            double cTax = (cTotal1 * 3.9) /100;
            String iTaxTotal = String.format("Rs %.1f", cTax);
            jtxtTax.setText(iTaxTotal);
            
            String iSubTotal = String.format("Rs %.1f", cTotal1);
            jtxtSubTotal.setText(iSubTotal);
            
            String iTotal = String.format("Rs %.1f", cTotal1  + cTax );
            jtxtTotal.setText(iTotal);
            
            String  BarCode  = String.format("Total is %.1f", cTotal1  + cTax );
            jtxtBarCode.setText(BarCode);
    }    
    //===========================================FUNCTION CHANGE======================
    
    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        
        double cTax = (sum * 3.9) /100;
        double cChange = (cash - (sum + cTax));
        
        String ChangeGiven = String.format("Rs %.1f",cChange );
        jtxtChange.setText(ChangeGiven);
        
        
    }
    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn7.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }     
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn8.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }     
                                         
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
      String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn9.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }     
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn4.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
           String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn5.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
            String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn6.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
            String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn1.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
            String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn2.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
            String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn3.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
               String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText (jbtn0.getText());
        }    
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
            jtxtDisplay.setText("");
            jtxtChange.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
            if (! jtxtDisplay.getText().contains("."))
            {
                jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
            }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnChickenSeekhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenSeekhActionPerformed
        double PriceOfItem = 220;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Seekh", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenSeekhActionPerformed

    private void jbtnChickenTikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenTikkaActionPerformed
        double PriceOfItem = 160;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Tikka", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenTikkaActionPerformed

    private void jbtnAlooSamoosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlooSamoosaActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Aloo Samoosa", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnAlooSamoosaActionPerformed

    private void jbtnBeefBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBeefBurgerActionPerformed
        double PriceOfItem = 350;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Beef Burger", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnBeefBurgerActionPerformed

    private void jbtnChickenBiryaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenBiryaniActionPerformed
        double PriceOfItem = 280;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Biryani", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenBiryaniActionPerformed

    private void jbtnChickenJalfreziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenJalfreziActionPerformed
        double PriceOfItem = 350;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Jalfrezi", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenJalfreziActionPerformed

    private void jbtnChickenKarahiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenKarahiActionPerformed
       double PriceOfItem = 750;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Karahi", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenKarahiActionPerformed

    private void jbtnChickenPulaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenPulaoActionPerformed
        double PriceOfItem = 1200;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Pulao", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenPulaoActionPerformed

    private void jbtnChickenSamoosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenSamoosaActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Samoosa", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenSamoosaActionPerformed

    private void jbtnGajrelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGajrelaActionPerformed
        double PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Gajrela", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnGajrelaActionPerformed

    private void jbtnGhullabJamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGhullabJamanActionPerformed
        double PriceOfItem = 600;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Ghullab Jaman", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnGhullabJamanActionPerformed

    private void jbtnHaleemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHaleemActionPerformed
        double PriceOfItem = 200;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Haleem", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHaleemActionPerformed

    private void jbtnHalwaPuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHalwaPuriActionPerformed
        double PriceOfItem = 120;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Halwa Puri", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHalwaPuriActionPerformed

    private void jbtnHotSpicyBiryaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHotSpicyBiryaniActionPerformed
        double PriceOfItem = 240;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Hot Spicy Biryani", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHotSpicyBiryaniActionPerformed

    private void jbtnZingerBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZingerBurgerActionPerformed
        double PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Zinger Burger", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnZingerBurgerActionPerformed

    private void jbtnHotChilliPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHotChilliPizzaActionPerformed
        double PriceOfItem = 550;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Hot Chilli Pizza", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHotChilliPizzaActionPerformed

    private void jbtnChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenBurgerActionPerformed
        double PriceOfItem = 220;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Chicken Burger", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChickenBurgerActionPerformed

    private void jbtnBeefSeekhKababActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBeefSeekhKababActionPerformed
       double PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Beef Seekh Kabab", "1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnBeefSeekhKababActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
             jtxtChange.setText("");
             jtxtDisplay.setText("");   
             }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat ("Printing in Progress");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
     
        try 
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          
          int RemoveItem = jTable1.getSelectedRow();
          if ( RemoveItem >= 0 )
          {
              model.removeRow(RemoveItem);
          }
          
          ItemCost(); 
    }//GEN-LAST:event_jbtnRemoveActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if You Want To Exit","Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        } 
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAboutActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Developed by Engr Muhammad Jamal Butt");
    }//GEN-LAST:event_jbtnAboutActionPerformed

    private void jbtnContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContactUsActionPerformed
        JOptionPane.showMessageDialog(rootPane, "+923463882550");
        JOptionPane.showMessageDialog(rootPane, "Hyper X Technologies");
    }//GEN-LAST:event_jbtnContactUsActionPerformed
    
        

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAbout;
    private javax.swing.JButton jbtnAlooSamoosa;
    private javax.swing.JButton jbtnBeefBurger;
    private javax.swing.JButton jbtnBeefSeekhKabab;
    private javax.swing.JButton jbtnChickenBiryani;
    private javax.swing.JButton jbtnChickenBurger;
    private javax.swing.JButton jbtnChickenJalfrezi;
    private javax.swing.JButton jbtnChickenKarahi;
    private javax.swing.JButton jbtnChickenPulao;
    private javax.swing.JButton jbtnChickenSamoosa;
    private javax.swing.JButton jbtnChickenSeekh;
    private javax.swing.JButton jbtnChickenTikka;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnContactUs;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGajrela;
    private javax.swing.JButton jbtnGhullabJaman;
    private javax.swing.JButton jbtnHaleem;
    private javax.swing.JButton jbtnHalwaPuri;
    private javax.swing.JButton jbtnHotChilliPizza;
    private javax.swing.JButton jbtnHotSpicyBiryani;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnZingerBurger;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
